package com.ws.driver_selenium.tests.hooks;

import io.qameta.allure.Allure;
import org.junit.jupiter.api.extension.BeforeAllCallback;
import org.junit.jupiter.api.extension.ExtensionContext;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.IOException;
import java.io.InputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Properties;

/**
 * JUnit 5 Extension chạy trước test đầu tiên, ghi file
 * {@code build/allure-results/environment.properties} với metadata về:
 * <ul>
 *   <li>Sinh viên thực hiện (tên, MSSV)</li>
 *   <li>Môn học, hệ thống test, trình duyệt</li>
 *   <li>Stack công nghệ: Selenium, JUnit 5, Allure</li>
 *   <li>Phiên bản Java, Gradle</li>
 * </ul>
 * <p>
 * File này được Allure Report đọc và hiển thị ở tab "Environment" trong report HTML.
 * <p>
 * Nếu file {@code allure-test.properties} tồn tại trong classpath (do người dùng cung cấp),
 * các key/value trong đó sẽ <strong>override</strong> giá trị mặc định.
 * <p>
 * Đăng ký bằng {@code @ExtendWith(EnvironmentWriter.class)} trên class test, hoặc cấu hình
 * global qua {@code junit-platform.properties}.
 */
public class EnvironmentWriter implements BeforeAllCallback {

    private static final Logger log = LoggerFactory.getLogger(EnvironmentWriter.class);

    /** Đường dẫn tuyệt đối tới file output (Allure sẽ đọc). */
    private static final String OUTPUT_PATH = "build/allure-results/environment.properties";

    /** Đường dẫn classpath tới file override (có thể không tồn tại). */
    private static final String OVERRIDE_RESOURCE = "/allure-test.properties";

    @Override
    public void beforeAll(ExtensionContext context) {
        log.info("EnvironmentWriter.beforeAll() được gọi cho class: {}",
                context.getRequiredTestClass().getSimpleName());
        Properties props = new Properties();
        loadDefaults(props);
        loadOverride(props);

        try {
            Path outputFile = Paths.get(OUTPUT_PATH);
            Files.createDirectories(outputFile.getParent());
            try (var writer = Files.newBufferedWriter(outputFile)) {
                props.store(writer, "Generated by EnvironmentWriter (auto-generated before test suite)");
            }
            log.info("Đã ghi {} với {} properties", outputFile.toAbsolutePath(), props.size());
        } catch (IOException e) {
            log.error("Không ghi được environment.properties: {}", e.getMessage(), e);
        }

        // Cũng gắn environment info vào Allure context để hiển thị trong report.
        props.forEach((k, v) -> Allure.parameter(String.valueOf(k), String.valueOf(v)));
    }

    /**
     * Nạp giá trị mặc định (hard-coded theo yêu cầu plan).
     */
    private void loadDefaults(Properties props) {
        props.setProperty("Sinh_Vien", "Ngo Minh Khoi");
        props.setProperty("MSSV", "6451071037");
        props.setProperty("Hoc_Phan", "Kiem thu phan mem");
        props.setProperty("He_Thong_Kiem_Thu",
                "Van phong dien tu UTC (https://vanphongdientu.utc.edu.vn/Login)");
        props.setProperty("Trinh_Duyet", "Google Chrome");
        props.setProperty("Framework", "Selenium 4 + JUnit 5 + Allure Report");
        props.setProperty("Java_Version", System.getProperty("java.version", "unknown"));
        props.setProperty("Gradle_Version", readGradleVersion());
    }

    /**
     * Nạp override từ classpath (nếu có). File phải ở {@code src/test/resources/}.
     * <p>
     * Nếu không có file override → bỏ qua (không lỗi).
     */
    private void loadOverride(Properties props) {
        try (InputStream is = EnvironmentWriter.class.getResourceAsStream(OVERRIDE_RESOURCE)) {
            if (is == null) {
                log.debug("Không tìm thấy {} trên classpath → dùng defaults", OVERRIDE_RESOURCE);
                return;
            }
            Properties override = new Properties();
            override.load(is);
            props.putAll(override);
            log.info("Đã load {} override từ {}", override.size(), OVERRIDE_RESOURCE);
        } catch (IOException e) {
            log.warn("Lỗi đọc {}: {}", OVERRIDE_RESOURCE, e.getMessage());
        }
    }

    /**
     * Đọc phiên bản Gradle runtime (fallback: {@code unknown}).
     */
    private String readGradleVersion() {
        try {
            // Gradle set system property "org.gradle.app.versions" ở task execution
            String v = System.getProperty("gradle.version");
            if (v != null && !v.isBlank()) {
                return v;
            }
            // Fallback: dùng package implementation version (khi chạy qua gradle wrapper)
            return String.valueOf(Runtime.version());
        } catch (Exception e) {
            return "unknown";
        }
    }
}
